### ISSUE TITLE
NoClassDefFoundError: com/google/api/client/http/AbstractInputStreamContent

### ISSUE THREAD

**Issue by Boomaa23** [Boomaa23/Note2JPG#11]
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/api/client/http/AbstractInputStreamContent
        at com.boomaa.note2jpg.config.Args.logic(Args.java:73)
        at com.boomaa.note2jpg.function.Main.main(Main.java:70)
Caused by: java.lang.ClassNotFoundException: com.google.api.client.http.AbstractInputStreamContent
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 2 more
```
It seems the JAR doesn't work with Google Drive. Tested it works with everything else, there just seems to be an issue here with drive.

**Comment by Boomaa23** [comment]
Fixed with manifest tweak, but now there's this
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/auth/oauth2/GoogleCredentials
        at com.boomaa.note2jpg.config.Args.logic(Args.java:73)
        at com.boomaa.note2jpg.function.Main.main(Main.java:70)
Caused by: java.lang.ClassNotFoundException: com.google.auth.oauth2.GoogleCredentials
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 2 more
```
